"""
World Module (V3.5 - Logical Body)

Goal: Environment = Infinite Sandbox.
Method: Execute Python code generated by the agent.
Constraint: No external datasets. Self-generated curriculum.
"""

import sys
import io
import traceback
from typing import Dict, Any, Tuple

class InternalSandbox:
    """
    The "World" where the ASI tests its hypotheses.
    It is a Python execution environment.
    """
    def __init__(self):
        self.global_context = {} # Persistent memory for the session

    def execute(self, code: str) -> Tuple[str, bool]:
        """
        Executes the given Python code string.
        Returns: (Output, Success)
        Output is stdout if success, or error message if fail.
        Success is True if no exception, False otherwise.
        """
        # Capture stdout
        old_stdout = sys.stdout
        redirected_output = io.StringIO()
        sys.stdout = redirected_output
        
        success = False
        output = ""
        
        try:
            # Execute in restricted global context
            # We allow the agent to define functions and variables that persist.
            exec(code, self.global_context)
            success = True
            output = redirected_output.getvalue()
            if not output:
                output = "[Success] (No Output)"
                
        except Exception:
            # Capture traceback
            success = False
            output = traceback.format_exc()
            
        finally:
            # Restore stdout
            sys.stdout = old_stdout
            
        return output, success

    def reset(self):
        self.global_context = {}
